In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_excel ('cancerdata.xlsx')

In [ ]:
x =df.drop(labels='diagnosis', axis=1)
x

           id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0      842302        17.99  ...          0.4601                  0.11890
1      842517        20.57  ...          0.2750                  0.08902
2    84300903        19.69  ...          0.3613                  0.08758
3    84348301        11.42  ...          0.6638                  0.17300
4    84358402        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564    926424        21.56  ...          0.2060                  0.07115
565    926682        20.13  ...          0.2572                  0.06637
566    926954        16.60  ...          0.2218                  0.07820
567    927241        20.60  ...          0.4087                  0.12400
568     92751         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [ ]:
y=pd.DataFrame(df.iloc[:,1])
y

    diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [ ]:
y.value_counts()
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
y=pd.DataFrame(y)
y

     0
0    1
1    1
2    1
3    1
4    1
..  ..
564  1
565  1
566  1
567  1
568  0

[569 rows x 1 columns]

In [ ]:
df.isna().sum()

id                         0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
#Z-Score Normalisation
scaler = StandardScaler()  
x = pd.DataFrame(scaler.fit_transform(x),columns=['id',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst'])
x

           id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0   -0.236405     1.097064  ...        2.750622                 1.937015
1   -0.236403     1.829821  ...       -0.243890                 0.281190
2    0.431741     1.579888  ...        1.152255                 0.201391
3    0.432121    -0.768909  ...        6.046041                 4.935010
4    0.432201     1.750297  ...       -0.868353                -0.397100
..        ...          ...  ...             ...                      ...
564 -0.235732     2.110995  ...       -1.360158                -0.709091
565 -0.235730     1.704854  ...       -0.531855                -0.973978
566 -0.235727     0.702284  ...       -1.104549                -0.318409
567 -0.235725     1.838341  ...        1.919083                 2.219635
568 -0.242406    -1.808401  ...       -0.048138                -0.751207

[569 rows x 31 columns]

In [ ]:
x1 = x.T
Cov_mat = pd.DataFrame(np.cov(x1))
Cov_mat

In [ ]:
values, vectors = np.linalg.eig(Cov_mat)

In [ ]:
tot_sum = sum(values)
print(tot_sum)

(370.15016144802087+0j)

In [ ]:
#PCA WITH 85% CONFIDENCE
projected_vector = []
sum_value = 0
i = 0
while sum_value < 0.85:
  sum_value += values[i]/tot_sum
  projected_vector.append(x.dot(vectors[i]))
  i+=1

In [ ]:
df1 = pd.DataFrame(projected_vector[0],columns=['PC1'])
for i in range(1, len(projected_vector)):
  df['PC{}'.format(i+1)] = projected_vector[i]
df1

          PC1
0   -2.593350
1    0.729203
2   -0.861348
3   -3.650929
4   -0.252979
..        ...
564 -0.250596
565 -0.061469
566  0.009862
567 -2.843121
568  1.650349

[569 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
lr=LogisticRegression()

In [ ]:
lr.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
ypredict = lr.predict(X_test)

In [ ]:
con_mat

array([[113,   0],
       [  3,  55]])

In [ ]:
sns.heatmap(con_mat,annot=True)

In [ ]:
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test, ypredict)

In [ ]:
from sklearn.metrics import accuracy_score 
accuracy_score(Y_test, ypredict)

0.9824561403508771

In [ ]:
print("PRECISION OF CLASS 1")
print(con_mat[0][0] / (con_mat[0][0] + con_mat[1][0]))
print()
print("PRECISION OF CLASS 2")
con_mat[1][1] / (con_mat[0][1] + con_mat[1][1])

PRECISION OF CLASS 1
0.9741379310344828

PRECISION OF CLASS 2

1.0

In [ ]:
print("RECALL OF CLASS 1")
print(con_mat[0][0] / (con_mat[0][0] + con_mat[0][1]))
print()
print("RECALL OF CLASS 2")
con_mat[1][1] / (con_mat[1][0] + con_mat[1][1])

RECALL OF CLASS 1
1.0

RECALL OF CLASS 2

0.9482758620689655